---
- name: add site config to nginx
  template:
    src: "nginx/site.j2"
    dest: "/etc/nginx/sites-available/{{ app_server_name }}"
  become: true
  notify:
      - restart nginx

- name: enable site config
  file:
    src: "/etc/nginx/sites-available/{{ app_server_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_server_name }}"
    state: link
  become: true
  notify:
    - restart nginx