---
app_user_name: "vagrant"
app_user_group: "vagrant"
app_server_name: "localdev.gw2gearopt.tichi.org"
app_deploy_path: "/home/{{ app_user_name }}/gitrepo"

forever_version: "0.15.2"

mongodb_version: "3.2.9"
mongodb_repo_version: "3.2"

nginx_version: "1.10.1*"

nodejs_version: "6.7.0"
npm_version: "3.10.8"