---
app_user_name: "gw2gearopt"
app_user_group: "gw2gearopt"
app_server_name: "localdev.gw2gearopt.tichi.org"

forever_version: "0.15.2"

mongodb_version: "3.2.9"
mongodb_repo_version: "3.2"

nginx_version: "1.10.1*"

nodejs_version: "6.7.0"
npm_version: "3.10.8"