---
- name: check required variables are set
  fail:
    msg: "{{ item }} is not defined"
  when: item not in hostvars[inventory_hostname]
  with_items:
    - app_user_name
    - app_server_name
    - app_deploy_path
    - app_deploy_key
    - app_deploy_repo
    - app_deploy_branch